### ISSUE TITLE
stg_customers contains PII data in the first_name and last_name columns so these need to be hashed.

### ISSUE THREAD

**Issue by jeremyhager** [jeremyhager/octo_jaffle_shop#3]
stg_customers contains PII data in the `first_name` and `last_name` columns so these need to be hashed. Move this model into a `src_seed/sensitive` directory and mark each of the sensitive columns as sensitive in the `src_seed/sensitive/_models.yml` using the syntax:  

```
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
        meta:
          sensitive: true
      - name: last_name
        meta:
          sensitive: true
```
