### ISSUE TITLE
SMT Dashboard: The customer count by month for customers making their first order

### ISSUE THREAD

**Issue by jeremyhager** [jeremyhager/octo_jaffle_shop#7]
There are two possible approaches to this:
1) -  How we do things at the time of writing - Create a final model per dashboard showing the relevant information and assign an exposure to each with a dummy URL :
     ```
     url: https://inksacio.eks.octopus.engineering/my_certification_dashboard/
     ```
   - Put each model into a directory specific to their business unit like `models/final/sales/fnl_sales_newcustomers.sql`
   - Make sure to write a `_models.yml` in each directory.
2) How we will do things in future - Make the required data available via [metrics](https://docs.getdbt.com/docs/build/metrics) configured directly on the warehouse model configs or in a `_metrics.yml` file. 

   For example:
   ```
   metrics:
   - name: new_customers
     label: New Customers
     model: ref('wh_customers')
     description: ""

     calculation_method: count_distinct
     expression: customer_id

     timestamp: first_order
     time_grains: [day, week, month, quarter, year]

     # general properties
     config:
       enabled: true 

     meta: {team: Sales}
   ```
